# Define o nome da aplicacao
spring.application.name=sistema

# Bloco de configuracao do banco de dados
# Define a URL de conexao com o banco. "localhost" eh a maquina local, "3306" eh a porta padrao do MariaDB, "gestao_devices" eh o banco que voce criou
spring.datasource.url=jdbc:mariadb://localhost:3306/lumisystemdan
# Define o usuario do banco. O XAMPP usa "root" por padrao
spring.datasource.username=root
# Define a senha do banco. O XAMPP nao define senha por padrao, entao fica vazio
spring.datasource.password=
# Define o driver JDBC que o Spring vai usar para se comunicar com o MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Bloco de configuracao do JPA e Hibernate
# Define o comportamento do Hibernate em relacao as tabelas. "create" apaga e recria as tabelas toda vez que o sistema sobe
spring.jpa.hibernate.ddl-auto=create
# Faz o Hibernate imprimir no console cada SQL que ele executar. Util para entender o que estAh acontecendo no banco durante o desenvolvimento
spring.jpa.show-sql=true
# Faz o Hibernate formatar o SQL impresso no console de forma legivel, com indentacao
spring.jpa.properties.hibernate.format_sql=true

# Removi a porta que era a 8081 para implantar o tomcat externo

# chave da API do google maps
google.maps.api.key=AIzaSyBgf5v7ozVAcl-uus5kaN8IgEAImw-lqQM

# senha do jwt para gerar e autenticar os tokens
jwt.secret=sua-chave-secreta-longa-aqui
# tempo de expiracao em milisegundos - equivalente a 50 minutos LEMBRAR DE MUDAR PARA 5 DEPOIS
jwt.expiration=3000000

# habilita o suporte a WebSocket nativo do JSF, necessario para o p:socket do PrimeFaces funcionar
joinfaces.faces.enable-websocket-endpoint=true

# para que o spring nao trate internamente e chame o globalexceptionhandler. nao quebra os try catch
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false